package server

import (
	"embed"
	"io/fs"
)

// embeddedWeb contains the production API-mode dashboard generated by
// `npm run build:embed`. Keeping the generated files in the repository makes
// ordinary `go build` invocations produce a self-contained atlas binary.
//
//go:embed webdist
var embeddedWeb embed.FS

func embeddedWebFS() fs.FS {
	web, err := fs.Sub(embeddedWeb, "webdist")
	if err != nil {
		// The go:embed pattern and the generated directory are compile-time
		// invariants. A panic here means the source tree is malformed.
		panic("cloudthreat atlas: embedded dashboard is unavailable: " + err.Error())
	}
	return web
}
